# Mainnet config for zebrad.

# The config format is documented here:
# https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html

# Usage:
#     zebrad generate -o myzebrad.toml
#     zebrad -c myzebrad.toml start
#
#     zebrad generate -o zebrad.toml
#     zebrad start
#
# If there is no -c flag on the command line, zebrad looks for zebrad.toml in
# the current directory. If that file does not exist, zebrad uses the default
# config.

[consensus]
checkpoint_sync = false
#checkpoint_sync = true

[network]
initial_mainnet_peers = [
# Global seeders
    'dnsseed.z.cash:8233',
    'dnsseed.str4d.xyz:8233',
    'mainnet.is.yolo.money:8233',
    'mainnet.seeder.zfnd.org:8233',

# Local instances
# zcashd
     '127.0.0.1:48233',
     '192.168.215.106:48233',
     '192.168.215.108:48233',
# zebrad
     '192.168.215.106:28233',
     '192.168.215.108:28233',
]
listen_addr = '0.0.0.0:28233'
network = 'Mainnet'
#peerset_initial_target_size = 25

[state]
cache_dir = '/home/dev/.cache/zebra-custom'
#debug_stop_at_height = 0

[sync]
#max_concurrent_block_requests = 1000
#lookahead_limit = 2000

[tracing]
filter = 'info'
#filter = 'trace'
#filter = 'info,zebrad=debug'
#filter = 'info,zebra_consensus=debug,zebra_chain=debug,zebra_script=debug,zebra_state=debug'
#filter = 'info,zebra_chain=debug,zebra_script=debug,zebra_state=debug,zebra_consensus::block[{}]=trace'

#flamegraph = 'flamegraph'
#endpoint_addr = '127.0.0.1:3000'

[metrics]
endpoint_addr = '0.0.0.0:9999'
